### ISSUE TITLE
Using local model to generate images using sdkit

### ISSUE THREAD

**Issue by yoou3-cyber** [easydiffusion/sdkit#1]
i have a trained local SD model 'sd-v1-4.ckpt' and i tried to use code from mainpage of sdkit to generate image
Before it i installed all nessecaries with comands in cmd:
`pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu116` and `pip install sdkit`, as cmd said they was installed succesfull
after it i run this code:
```
import sdkit
from sdkit.models import load_model
from sdkit.generate import generate_images

from sdkit.utils import save_images, log

context = sdkit.Context()

# set the path to the model file on the disk (.ckpt or .safetensors file) 
context.model_paths['stable-diffusion'] = 'C:\\Users\\Roman\\Downloads\\sd-v1-4.ckpt'
load_model(context, 'stable-diffusion') 

# generate the image
images = generate_images(context, prompt='Photograph of an astronaut riding a horse', seed=42, width=512, height=512)

# save the image
save_images(images, dir_path='C:\\Users\\Roman\\Downloads')
```

and then i got error code in cmd:
```
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "C:/Users/Roman/Downloads/dal.py", line 3, in <module>
    from sdkit.generate import generate_images
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\sdkit\generate\__init__.py", line 1, in <module>
    from .image_generator import (
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\sdkit\generate\image_generator.py", line 3, in <module>
    from pytorch_lightning import seed_everything
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\pytorch_lightning\__init__.py", line 21, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\pytorch_lightning\callbacks\__init__.py", line 24, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\pytorch_lightning\callbacks\pruning.py", line 31, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\pytorch_lightning\core\__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\pytorch_lightning\core\lightning.py", line 41, in <module>
    from pytorch_lightning.trainer.connectors.logger_connector.fx_validator import FxValidator
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\pytorch_lightning\trainer\__init__.py", line 18, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\pytorch_lightning\trainer\trainer.py", line 31, in <module>
    from pytorch_lightning.loggers import LightningLoggerBase
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\pytorch_lightning\loggers\__init__.py", line 26, in <module>
    from pytorch_lightning.loggers.wandb import _WANDB_AVAILABLE, WandbLogger  # noqa: F401
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\pytorch_lightning\loggers\wandb.py", line 37, in <module>
    _WANDB_GREATER_EQUAL_0_10_22 = _compare_version("wandb", operator.ge, "0.10.22")
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\pytorch_lightning\utilities\imports.py", line 54, in _compare_version
    pkg = importlib.import_module(package)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_init.py", line 30, in <module>
    from . import wandb_login, wandb_setup
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_login.py", line 25, in <module>
    from .wandb_settings import Settings, Source
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_settings.py", line 39, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_setup.py", line 23, in <module>
    from .lib import config_util, server, tracelog
  File "C:\Users\Roman\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\lib\tracelog.py", line 48, in <module>
    stdout_write = sys.__stdout__.write
AttributeError: 'NoneType' object has no attribute 'write'
```
how can i repair it?

**Comment by cmdr2** [comment]
Hi @yoou3-cyber, two comments:
1. It looks like the `pytorch-lightning` module is showing an error. Can you please share the output of `pip show pytorch-lightning`
2. Can you try using Python 3.8? I see that you're using 3.10, and I wonder if pytorch works okay (with CUDA) in that version.

Thanks for trying this out, this is useful feedback!

Cheers

**Comment by yoou3-cyber** [comment]
Sure:
1/Name: pytorch-lightning
Version: 1.4.2
Summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML
researchers. Scale your models. Write less boilerplate.
Home-page: https://github.com/PyTorchLightning/pytorch-lightning
Author: William Falcon et al.
Author-email: ***@***.***
License: Apache-2.0
Location: c:\users\roman\appdata\roaming\python\python310\site-packages
Requires: fsspec, future, numpy, packaging, pyDeprecate, PyYAML,
tensorboard, torch, torchmetrics, tqdm, typing-extensions
Required-by: stable-diffusion-sdkit
2. i am running SD on cpu , bcos i have no nvidia card, is there any method
to use sdkit with Radeon RX6600M or just use cpu?

вс, 25 дек. 2022 г. в 17:36, cmdr2 ***@***.***>:

**Comment by cmdr2** [comment]
Hi, can you please try with Python 3.8 as well? Thanks
