### ISSUE TITLE
circular import error

### ISSUE THREAD

**Issue by elbowdonkey** [easydiffusion/sdkit#49]
**Describe the bug**

After setting up a virtual env using python 3.10.0, I followed the installation steps describe for Mac:

```
pip install sdkit
```

Then, when trying to run the example code, I see this:

```
# example.py
import sdkit
from sdkit.models import load_model
```

```
python example.py
```

```
Traceback (most recent call last):
  File "[masked]/projects/sdkit-api/example.py", line 24, in <module>
    from sdkit.models import load_model
  File "[masked]/.pyenv/versions/3.10.0/lib/python3.10/site-packages/sdkit/models/__init__.py", line 1, in <module>
    from .model_downloader import (
  File "[masked]/.pyenv/versions/3.10.0/lib/python3.10/site-packages/sdkit/models/model_downloader.py", line 4, in <module>
    from sdkit.utils import download_file, log
  File "[masked]/.pyenv/versions/3.10.0/lib/python3.10/site-packages/sdkit/utils/__init__.py", line 43, in <module>
    from .misc_utils import make_sd_context, get_nested_attr
  File "[masked]/.pyenv/versions/3.10.0/lib/python3.10/site-packages/sdkit/utils/misc_utils.py", line 2, in <module>
    from sdkit.models import load_model
ImportError: cannot import name 'load_model' from partially initialized module 'sdkit.models' (most likely due to a circular import) ([masked]/.pyenv/versions/3.10.0/lib/python3.10/site-packages/sdkit/models/__init__.py)
```

**Environment (please complete the following information):**
 - OS (with OS version): macOS 13.4.1 (c) 
 - Python version: 3.10.0

**Comment by elbowdonkey** [comment]
I'm not a python developer, so I'm not super familiar with how it handles loading of files, but I managed to cobble this together after looking at the tests for sdkit. This appears to work:

```
from sdkit import Context
from sdkit.generate import generate_images
from sdkit.models import load_model
from sdkit.utils import diffusers_latent_samples_to_images, img_to_buffer

context = Context()
context.model_paths['stable-diffusion'] = 'path_to_model'
load_model(context, 'stable-diffusion')
images = generate_images(context, prompt='Photograph of an astronaut riding a horse', seed=42, width=512, height=512)

# save the image
save_images(images, dir_path='.')

log.info("Generated images!")
```

**Comment by cmdr2** [comment]
Thanks, pushed a fix for this. Apologies for the delay.
