### ISSUE TITLE
Stable Diffusion XL problem

### ISSUE THREAD

**Issue by Benji4564** [easydiffusion/sdkit#57]
When I try to run 

```
import sdkit
from sdkit.models import load_model
from sdkit.generate import generate_images
from sdkit.utils import save_images, log

context = sdkit.Context()

# set the path to the model file on the disk (.ckpt or .safetensors file)
context.model_paths['stable-diffusion'] = 'models/imageGeneration/stable-diffusion/xl/sd_xl_base_1.0.safetensors'
load_model(context, 'stable-diffusion')

# generate the image
images = generate_images(context, prompt='Photograph of an astronaut riding a horse', seed=42, width=512, height=512)

# save the image
save_images(images, dir_path='D:\\path\\to\\images\\directory')

log.info("Generated images!")
```

using SD XL I get the following error:

```
# Traceback (most recent call last):
#   File "c:\Users\Test\Desktop\backend\test.py", line 101, in <module>
#     load_model(context, 'stable-diffusion')
#   File "C:\Users\Test\miniconda3\envs\Inference\lib\site-packages\sdkit\models\model_loader\__init__.py", line 45, in load_model
#     context.models[model_type] = get_loader_module(model_type).load_model(context, **kwargs)
#   File "C:\Users\Test\miniconda3\envs\Inference\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.py", line 87, in load_model
#     config.model.params.unet_config.params.use_fp16 = context.half_precision
#   File "C:\Users\Test\miniconda3\envs\Inference\lib\site-packages\omegaconf\dictconfig.py", line 353, in __getattr__
#     self._format_and_raise(
#   File "C:\Users\Test\miniconda3\envs\Inference\lib\site-packages\omegaconf\base.py", line 190, in _format_and_raise
#     format_and_raise(
#   File "C:\Users\Test\miniconda3\envs\Inference\lib\site-packages\omegaconf\_utils.py", line 821, in format_and_raise
#     _raise(ex, cause)
#   File "C:\Users\Test\miniconda3\envs\Inference\lib\site-packages\omegaconf\_utils.py", line 719, in _raise
#     raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
#   File "C:\Users\Test\miniconda3\envs\Inference\lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
#     return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
#   File "C:\Users\Test\miniconda3\envs\Inference\lib\site-packages\omegaconf\dictconfig.py", line 438, in _get_impl
#     node = self._get_node(key=key, throw_on_missing_key=True)
#   File "C:\Users\Test\miniconda3\envs\Inference\lib\site-packages\omegaconf\dictconfig.py", line 470, in _get_node
#     raise ConfigKeyError(f"Missing key {key}")
# omegaconf.errors.ConfigAttributeError: Missing key unet_config
#     full_key: model.params.unet_config
#     object_type=dict
```

Is stable diffusion xl not supported or do I have to do any other steps

**Comment by cmdr2** [comment]
Hi @Benji4564 Please include the `test_diffusers` flag in the context variable. New features like SDXL, LoRAs, embeddings etc are in beta, and require the test_diffusers flag.

For e.g.
```py
context = sdkit.Context()
context.test_diffusers = True
```

This flag won't be necessary in a few weeks, once the new features become stable.

Thanks, please feel free to reopen if this doesn't work.
