### ISSUE TITLE
Error when running the example code in the README

### ISSUE THREAD

**Issue by DisableGraphics** [easydiffusion/sdkit#74]
**Describe the bug**
When running the example code provided in the README.MD, the following error appears:
```
/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/transformers/utils/generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/transformers/utils/generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
11:04:15.326 INFO MainThread loading stable-diffusion model from 768-v-ema.safetensors to device: cuda:0
No module 'xformers'. Proceeding without it.
11:04:15.329 ERROR MainThread ERROR: parsing pickle in 768-v-ema.safetensors: 
/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
Traceback (most recent call last):
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/diffusers/utils/import_utils.py", line 809, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 61, in <module>
    from .watermark import StableDiffusionXLWatermarker
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion_xl/watermark.py", line 8, in <module>
    from imwatermark import WatermarkEncoder
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/imwatermark/__init__.py", line 1, in <module>
    from .watermark import WatermarkEncoder, WatermarkDecoder
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/imwatermark/watermark.py", line 5, in <module>
    import cv2
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/disablegraphics/server-py/main.py", line 10, in <module>
    load_model(context, 'stable-diffusion')
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/sdkit/models/model_loader/__init__.py", line 54, in load_model
    context.models[model_type] = get_loader_module(model_type).load_model(context, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/sdkit/models/model_loader/stable_diffusion/__init__.py", line 86, in load_model
    return load_diffusers_model(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/sdkit/models/model_loader/stable_diffusion/__init__.py", line 156, in load_diffusers_model
    from diffusers import (
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/diffusers/utils/import_utils.py", line 800, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/diffusers/utils/import_utils.py", line 800, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/diffusers/utils/import_utils.py", line 799, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/disablegraphics/server-py/venv/lib/python3.11/site-packages/diffusers/utils/import_utils.py", line 811, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl because of the following error (look up to see its traceback):
numpy.core.multiarray failed to import
```

**To Reproduce**
Install dependencies as instructed in the README. This is how I did it:
```
python3.11 -v venv venv
source venv/bin/activate
pip3.11 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu116
pip3.11 install sdkit
```
I'm using pip3.11 because my system also has python3.12, with whom tokenizers refuses to compile.
**Expected behavior**
I'd expect sdkit to generate the image.

**Screenshots**
No need for them, I believe.

**Environment (please complete the following information):**
 - OS (with OS version): ArcoLinux (Arch linux). Latest version.
 - Python version: 3.11.9

**Additional context**
I made another sdkit-based app around february, and it worked perfectly fine (good job making this library btw), so I don't know why I'm getting these errors only 4 months later.

**Comment by DisableGraphics** [comment]
The issue is in numpy. Version 2.0.0 has broken existing programs that use it, so downgrade to the previous version of numpy (1.26.4) is the solution.

Do so with `pip install numpy==1.26.4`
